// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3VVfs8rcWMUABRDoEjbOT4migASRAIoI',
    appId: '1:925576488292:web:3d4ee891d8963182fa4671',
    messagingSenderId: '925576488292',
    projectId: 'rentstuff-app',
    authDomain: 'rentstuff-app.firebaseapp.com',
    storageBucket: 'rentstuff-app.firebasestorage.app',
    measurementId: 'G-VX5LHCYRPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc3M27MB3H0KaBHtY6PJLjtHxmVfgqIFU',
    appId: '1:925576488292:android:fc29a3d2a4803eecfa4671',
    messagingSenderId: '925576488292',
    projectId: 'rentstuff-app',
    storageBucket: 'rentstuff-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRi7XTnG36kTfxMxgeRnAvI6cTBBgtDJM',
    appId: '1:925576488292:ios:97f633b998be205afa4671',
    messagingSenderId: '925576488292',
    projectId: 'rentstuff-app',
    storageBucket: 'rentstuff-app.firebasestorage.app',
    iosBundleId: 'com.example.rentstuff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRi7XTnG36kTfxMxgeRnAvI6cTBBgtDJM',
    appId: '1:925576488292:ios:97f633b998be205afa4671',
    messagingSenderId: '925576488292',
    projectId: 'rentstuff-app',
    storageBucket: 'rentstuff-app.firebasestorage.app',
    iosBundleId: 'com.example.rentstuff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3VVfs8rcWMUABRDoEjbOT4migASRAIoI',
    appId: '1:925576488292:web:e2034106af4b1f78fa4671',
    messagingSenderId: '925576488292',
    projectId: 'rentstuff-app',
    authDomain: 'rentstuff-app.firebaseapp.com',
    storageBucket: 'rentstuff-app.firebasestorage.app',
    measurementId: 'G-2BL9LQFLN1',
  );

}